### ISSUE TITLE
ObjectDeclarations::getFunctions()

### ISSUE THREAD

**Issue by GaryJones** [PHPCSStandards/PHPCSUtils#124]
Idea: Have a way to check if a class contains a particular method.

```
Class::containsMethod( string $class, string $method_name );
```

Instead of a `string $class`, perhaps a `$stackPtr` could be used instead.

**Comment by jrfnl** [comment]
This is related to something I have been thinking about already: a method to retrieve the method names of all methods declared in a class.

The code would then becomes something like:
```php
$methods = Class::getMethodNames($phpcsFile, $stackPtr);
if (isset($methods[$targetMethod])) {
    // Do something.
}
```

Just keep in mind that any utility method which has to walk a large chunk of code is highly inefficient.

So, again, my question is: can you make the use-case more specific ? Can you give some examples of sniffs for which this would be useful ?

It might be better to create an abstract class as a base instead.

**Comment by jrfnl** [comment]
@GaryJones Have a look at #592. I believe that PR addressed this request along the lines of the comment I posted before.
