### ISSUE TITLE
Function::existsInFile()

### ISSUE THREAD

**Issue by GaryJones** [PHPCSStandards/PHPCSUtils#125]
Idea: Have a way to see if a particular function is defined in the current file:

```
Functions::existsInFile( string $function_name );
```

**Comment by jrfnl** [comment]
Can you make the use-case more specific ? (Also see my answer here: https://github.com/PHPCSStandards/PHPCSUtils/issues/124#issuecomment-605652175 )

**Comment by GaryJones** [comment]
May be better to look at this from a `File::containsFunction( $function_name )`, in which case #122 would cover this.
