### ISSUE TITLE
Short arrow functions as arguments, Multi-line function call not indented correctly

### ISSUE THREAD

**Issue by petemcfarlane** [PHPCSStandards/PHPCSUtils#244]
Hi I've noticed a false-positive/conflicting issue with multi-line function call when using short arrow functions, here is a shrunken example:
```php
// test.php
<?php 
$data = array_map(
    fn () => array_merge(
        [1, 2],
        [3, 4],
    ),
    [1, 2, 3]
);
```

running 
```
phpcs --standard=PSR2 test.php
```
results in 
```
------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
------------------------------------------------------------------------------------------------
 5 | ERROR | [x] Multi-line function call not indented correctly; expected 4 spaces but found 8
 6 | ERROR | [x] Multi-line function call not indented correctly; expected 4 spaces but found 8
------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
------------------------------------------------------------------------------------------------
```

But if I change the indentation to 4 as it suggests like so
```php
$data = array_map(
    fn () => array_merge(
    [1, 2],
    [3, 4],
    ),
    [1, 2, 3]
);
```

and run again I get the opposite warning
```
------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
------------------------------------------------------------------------------------------------
 5 | ERROR | [x] Multi-line function call not indented correctly; expected 8 spaces but found 4
 6 | ERROR | [x] Multi-line function call not indented correctly; expected 8 spaces but found 4
------------------------------------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
------------------------------------------------------------------------------------------------
```

It's worth noting it only seems to happen inside another function, this is fine for example:

```php
$function = fn () => array_merge(
    [1, 2],
    [3, 4],
);
```

```bash
> phpcs --version
PHP_CodeSniffer version 3.5.0 (stable) by Squiz (http://www.squiz.net)
> php -v
PHP 7.4.13 (cli) (built: Nov 30 2020 14:46:04) ( NTS )
```

**Comment by jrfnl** [comment]
@petemcfarlane PHPCS itself - which contains the PSR2 standard - does not use PHPCSUtils, so this is nothing to do with this repo. Please report your issue upstream: https://github.com/squizlabs/php_codesniffer/

**Comment by jrfnl** [comment]
@petemcfarlane I just noticed you added some more info in the original ticket description. You seem to be using PHPCS 3.5.0, while the latest version is 3.5.8.
While 3.5.0 is _runtime_ compatible with PHP 7.4, it doesn't contain full syntax support for PHP 7.4 yet. For that you need PHPCS 3.5.6 minimum.

In other words: please update your PHPCS install and chances are the issue is already fixed.

**Comment by petemcfarlane** [comment]
Thank you, I had 5.0.8 in the project but I forgot I had an old version (5.0.0) installed globally - that was taking precedence 🤦
And I also slipped and hit return before I’d finished writing the issue so double 🤦🤦
As you kindly suggested, this issue was indeed fixed somewhere along the way. Thanks

**Comment by jrfnl** [comment]
@petemcfarlane Glad to hear it and happy to hear its solved now.
