### ISSUE TITLE
Rename `master` to `stable`

### ISSUE THREAD

**Issue by jrfnl** [PHPCSStandards/PHPCSUtils#290]
This rename can only happen **_just_** before a new release is published as it would take down the GH Pages website which is tied to the `master` branch and to bring the site back up a commit to the `stable` branch would be needed, and as commits to that branch are only done on release, the timing of the rename is important.

**Comment by jrfnl** [comment]
Refs:
* https://stevenmortimer.com/5-steps-to-change-github-default-branch-from-master-to-main/
* https://github.com/github/renaming
* https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main

**Comment by jrchamp** [comment]
In case this is helpful: The first and third references mostly use the "create a new branch then change the default branch" approach. I had a much better experience with [GitHub's web-based branch renaming](https://github.com/github/renaming#renaming-existing-branches) functionality (from your second reference) as it automatically performed all of the tasks I was planning to do manually (creating the new branch, changing the default branch, switching PR targets, etc).
