### ISSUE TITLE
Boolean handling

### ISSUE THREAD

**Issue by szepeviktor** [PHPCSStandards/PHPCSUtils#424]
There are about 300 boolean checks mostly in `if`-s.
`if` expects a boolean but we have `$boolean === false` instead. (and of course `=== true`)

It would be nice to remove these conditions.

**Comment by jrfnl** [comment]
Sorry, but no. I prefer to be explicit and lean towards the coding style required by PHP_CodeSniffer itself in that (though I don't enforce the same).
